name: contaminados

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          cd BE/Contaminados
          dotnet restore

      - name: Build
        run: |
          cd BE/Contaminados
          dotnet build --configuration Release

  publish-Api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Push Image
        run: |
          cd BE/Contaminados
          docker image build -t luisballar/contaminados:latest .
          echo "${{ secrets.DOCKERHUBPASSCONTAMINADOS }}" | docker login -u "luismarioballar@gmail.com" --password-stdin
          docker push luisballar/contaminados:latest
